### ISSUE TITLE
"Allow Video" setting on ReviewsX Pro

### ISSUE THREAD

**Issue by almcgough** [reviewx/Contribute#1]
Please make it so we can disable video upload, but allow video link via external URL. At present, enabling "Allow Video" enables both. I know most people will never allow users to upload video to system, but certainly will allow external url because we would love a video review.

**Comment by arnaimbd** [comment]
Hey @almcgough, sounds very interesting and logical as well. 
We'll be happy to introduce this setting so you'll be able to enable/disable the video form 'External & Internal' sources separately. 

Also added this setting into our public roadmap: https://trello.com/c/JWItjTRT 
You can vote to proceed it faster. And we'll keep you posted the updates. Thank you.

**Comment by arnaimbd** [comment]
Hey @almcgough,

I'm very excited to let you know that we have just released 🚀 a setting to allow the video attachment from the internal AND/OR external sources, as you mentioned. Full [changelogs](https://reviewx.io/changelog/).

Please find the [documentation with visual graphics]( https://reviewx.io/docs/how-to-enable-internal-or-external-source-for-video-attachment-separately/)

For any further inquiries please feel free to let us know.
You can also join our [Facebook community](https://www.facebook.com/groups/reviewx)

Cheers!

**Comment by almcgough** [comment]
That’s really great, thank you for completing this request.


 <https://img.newoldstamp.com/r/331450/p>	
Adam McGough
mfe Design
Web Design & Development
 
phone: 888.284.4684
site: mfedesign.com <https://img.newoldstamp.com/r/331450/w>
email: info@mfedesign.com <mailto:info@mfedesign.com>	
 <https://img.newoldstamp.com/r/331450/facebook>
 <https://img.newoldstamp.com/r/331450/twitter>
 <https://img.newoldstamp.com/r/331450/linkedin>
 
 <https://img.newoldstamp.com/r/331450/b>


On Oct 6, 2020, at 1:30 PM, Arifur Rahman Naim <notifications@github.com> wrote:


Hey @almcgough <https://github.com/almcgough>,

I'm very excited to let you know that we have just released 🚀 a setting to allow the video attachment from the internal AND/OR external sources, as you mentioned. Full changelogs <https://reviewx.io/changelog/>.

Please find the documentation with visual graphics <https://reviewx.io/docs/how-to-enable-internal-or-external-source-for-video-attachment-separately/>
For any further inquiries please feel free to let us know.
You can also join our Facebook community <https://www.facebook.com/groups/reviewx>
Cheers!

**Comment by arnaimbd** [comment]
@almcgough, mate, I'm so glad that you do appreciate our efforts 🤩

You can also consider leaving a 5-star review and that'll encourage us to make ReviewX more awesome every day: https://wordpress.org/support/plugin/reviewx/reviews/#new-post

While you're using the plugin if you having any further issues, please feel free to let us know and we'll try out best to resolve.

Thank you 😊
