### ISSUE TITLE
Shortcode not working

### ISSUE THREAD

**Issue by sarnetski** [reviewx/Contribute#10]
Hi,
Shortcode not working..
![Screenshot_1](https://user-images.githubusercontent.com/77154441/104015403-df76cc80-51b4-11eb-81d0-fe1a57e5860b.png)

**Comment by amin-abir** [comment]
Hi @sarnetski 

In this screenshot these are not shortcodes, This is the test email template, and the data of these third brackets ( [ ] ) will dynamically change with actual data when the email is sent to your customer.
Like [SHOP_NAME] will be changed by your shop name, [ORDER_ID] will be replaced by the actual order id number.

Test email is for testing purpose, that email is sent or not, also to check the email content.

Thanks

**Comment by arnaimbd** [comment]
Hi @sarnetski, 
Thanks for reporting the issue.

@sarnetski, Can you please confirm that you are sending the TEST email or the real email.

If you send the test email, we display the email preset/shortcode as we don't have the real information to show. But when you send the email for real purposes, all those preset/shortcodes will be manipulated by the real data.

If you have any further inquiries, please feel free to let us know here: https://reviewx.io/support/

Thank you 😊

**Comment by sarnetski** [comment]
Yeap, that was test email. 

Plugin is not working for me. It does not show up
![Screenshot_2](https://user-images.githubusercontent.com/77154441/104017787-06cf9880-51b9-11eb-99c6-f8f676cd760a.png)
![Screenshot_3](https://user-images.githubusercontent.com/77154441/104017880-32528300-51b9-11eb-85d1-173b2dcce41b.png)

**Comment by arnaimbd** [comment]
@sarnetski, sorry for the inconvenience. 
Can you please share your website URL? Thanks.
