### ISSUE TITLE
Duplicate review should not be posted

### ISSUE THREAD

**Issue by nomirobin** [reviewx/Contribute#12]
Hello, I have used your plugin, you should add a function which can stop all users to post duplicate review. Currently it is working fine like If I posted a review once and if again I post the same review from same account, then it will give me duplicate review error.

But If the other user post the same review then it is accepting it and letting the user to post the comment, while it should give the error to user that this review has been already posted by another user.

Can you do such thing?

**Comment by amin-abir** [comment]
Hi @nomirobin 

That's an interesting feature you are talking about. As we use here WordPress default error message for duplicate review for the same user, but  let me talk with my developer about the scenario you are talking about.

I will inform you once I get updates from that end.

Thanks for using ReviewX.

Amin

**Comment by nomirobin** [comment]
Thank you, I appreciate your work. I will be awaiting for this feature.

**Comment by amin-abir** [comment]
Hi @nomirobin 

I have discussed this with the developer. As I earlier said, we are using the WordPress default comments system, and the duplicate comments checking is also managed by WordPress for the same user. After checking some use cases, I think currently it is not feasible to introduce a feature on ReviewX where the system checks the same comments for different users.

I hope you will understand 😊. Thanks for using ReviewX.

Regards

Amin
