### ISSUE TITLE
Error Duplicate Pagination + Suggest

### ISSUE THREAD

**Issue by vuthanhcong1993** [reviewx/Contribute#13]
https://user-images.githubusercontent.com/19855226/109453896-b45a7c00-7a85-11eb-9354-304dec68c49e.jpg
Not show review in last pagination
https://user-images.githubusercontent.com/19855226/109453484-c687ea80-7a84-11eb-965d-7de5e695d8a4.jpg
Duplicate Pagination

Suggest: Please auto enable review statics when 0 review tks you!

**Comment by amin-abir** [comment]
Hi @vuthanhcong1993 

Sorry for your inconvenience. Can you please contact our support? https://reviewx.io/support/

Our support team will look after that quickly.

Thanks for using ReviewX.😊

**Comment by vuthanhcong1993** [comment]
> Hi @vuthanhcong1993
> 
> Sorry for your inconvenience. Can you please contact our support? https://reviewx.io/support/
> 
> Our support team will look after that quickly.
> 
> Thanks for using ReviewX.😊

OK ^^
