### ISSUE TITLE
Image review issue and on mobile screen issue

### ISSUE THREAD

**Issue by heiheiheihei9** [reviewx/Contribute#14]
1, Is it possible to let user upload the image without using the upload sistem of wordpress, and  make it dynamically.
(For example, if I uploaded a wrong picture, and I want to delete it from this site. but the picture remains in the library and I cannot delete it)
2,On the product page, when a user cancels the upload image, the field for uploading image just disappears!
3, Making the order template more mobile friendly: two buttons on each line instead of one, remove the string "action"

**Comment by amin-abir** [comment]
Hi @heiheiheihei9 

Let me answer the questions.

1. We are using the WordPress media library, so it is not possible to use a separate upload system. We have an edit review option in our pro version, so if someone uploaded the wrong picture, he can remove the image attachments, or the admin also has the access to edit/delete/upload images with that review.

2.  Its the site owner's choice, he can enable/ disable the image upload option for his users from the settings. Its not mandatory for a user to upload an image, I am not clear 'when a user cancels the upload image'

3. I am not sure the ‘action’ string you mentioned, is related to our plugin, as we do not have such a button. Actually, in the order table, we have two buttons ‘view’ & ‘submit/view review’ for our free version.https://prnt.sc/11cehuk
And three buttons ‘view’, ‘submit/view review’, ‘edit review’ in our pro version https://prnt.sc/11ceh3v

And, we may think to display two buttons in two rows, but I think in our pro version, it will not look good to display 3 buttons in two rows.

Thanks
