### ISSUE TITLE
How can i change thats title

### ISSUE THREAD

**Issue by agenciadiglab** [reviewx/Contribute#16]
![image](https://user-images.githubusercontent.com/85712754/121606193-141cd780-ca24-11eb-8962-5c95ed6cf4ce.png)

How can i change this title 'There are no reviews yet.' to portuguese?

also 'Be the first to review' ... 

tnks

**Comment by amin-abir** [comment]
ReviewX is fully translatable. Using Loco Translate plugin the mentioned title can be translated.
