### ISSUE TITLE
Reminder emails not being scheduled when order status is changed via the WooCommerce Mobile App

### ISSUE THREAD

**Issue by mikeparsons42** [reviewx/Contribute#19]
I have one of my sites setup to send reminder emails to customers 7 days after their order status is set to "Completed".

This works 100% if I use the Wordpress admin to update an orders status, however if I use the official WooCommerce mobile app to update the order status then it never enters the scheduled queue.

Can you please take a look to see if there is an additional hook or event that can be used to ensure these orders don't get missed?

Thanks for all your hard work :)

**Comment by amin-abir** [comment]
Hi @schnipz 

Thanks for pointing out that. Please allow us some to check the scenario. Also, we may need some more information, it will be good if your please open a ticket [here](https://reviewx.io/support/).

Glad to know you like our plugin.

Thanks and regards

Amin

**Comment by mikeparsons42** [comment]
@amin-abir Done 👍 Thank you
