### ISSUE TITLE
Bugs and features

### ISSUE THREAD

**Issue by m12wong** [reviewx/Contribute#2]
When a customer leaves a review the star ratings are not saved. I have to manual edit the review and enter in the star rating. 0 star ratings are showing in the graph but can't see any reviews with 0 stars.

The title where it says 'Reviewd by x customers(s)' the x is not showing the proper number of customer reviews.

**Comment by arnaimbd** [comment]
Hi @m12wong, thanks for reporting the issue. We'll inspect the issue right away and will let you know the updates.

**Comment by beyond88** [comment]
Hi @m12wong, Would you please share the website URL to detect the issue?

**Comment by amin-abir** [comment]
Hi @m12wong 
Can you please share your site URL, from where you are facing problem?
It will help us to inspect the issue quickly.

Thanks

**Comment by m12wong** [comment]
Hi,

 


https://goldenbud.net/product/shroomology-microdose-psilocybe-mushrooms-9000mg/

 

This product is showing 0 star reviews but there is none.

 

And the other bugs i mentioned in GitHub

 

Thank you.

 

Sent: Wednesday, September 23, 2020 at 12:32 AM

**Comment by amin-abir** [comment]
Hi @m12wong 

You shared link shows under maintenance page. Can you please share your site access to us, it will help us to investigate the scenario, also will find a quick solution .
You can send your site access here, if you want, or in our mail:  support@reviewx.io

**Comment by m12wong** [comment]
Sorry, I'm in zombie mode no sleep. I disable plugin site is working now.

 

https://goldenbud.net/wp-admin/

User: goldenbud@gmx.com
pass: @Goldenbud23

 

Thanks

 
 

Sent: Wednesday, September 23, 2020 at 1:43 AM

**Comment by amin-abir** [comment]
Thanks, we are working on it

**Comment by arnaimbd** [comment]
Resolved through support email. Thanks for your cooperation :)
