### ISSUE TITLE
Filter & send reminder 

### ISSUE THREAD

**Issue by Areefy** [reviewx/Contribute#21]
Hi, I’m testing this plugin for my site before purchasing the premium version for WordPress. However, filter & send reminder causing trouble.

1. Every time I log out from wp, filter & send reminder reset to default to order status pending payment option.
2. When I change back the order status to complete, it sends the reminder emails to previous recipients, who were all ready summited reviews.
3. It also cc(d) reminder emails to my wp-admin account.

If you could let me know, how to resolve this, that would be great.

Regards

**Comment by amin-abir** [comment]
Hi @Areefy 

Hope you are fine and doing great.😊

Thanks for your interest in ReviewX. Can you please contact our [support](https://reviewx.io/support/)? As we need some more information, so it will be helpful for us from our support forum.

Regards.
