### ISSUE TITLE
REVIEWX issues

### ISSUE THREAD

**Issue by JAWWDROPP** [reviewx/Contribute#22]
ReviewX seems to have completely stopped working on my website. Neither can pictures be uploaded and neither can any reviews in text be posted as well! Please help me out

**Comment by amin-abir** [comment]
Hi @JAWWDROPP 

Hope you are fine and doing great.😊

Sorry to hear about your inconvenience.  We have received your tickets in our support. Our support team will take care of this.

Thanks
