### ISSUE TITLE
plugins is breaking my website 

### ISSUE THREAD

**Issue by scayver** [reviewx/Contribute#23]
Hello there is an issue with the pro version of the plugin that's break up my website everytime I activate it. I am not sure what's casing I just wanted to get this to your attention. 🙏

**Comment by scayver** [comment]
https://d.pr/i/pwfsZN

The images are broken and not working corrected I hope the next update fix this issue.

**Comment by amin-abir** [comment]
Hi @scayver 

Hope you are fine and enjoying your holiday.😊

Sorry to hear about your inconvenience. There could be a chance to conflict with another plugin. As we may need some extra information so, it will be helpful if you contact our [support](https://reviewx.io/support/). Our dedicated support team member will take care of this issue.

Thanks for using ReviewX.

Regards
