### ISSUE TITLE
can’t submit comment 

### ISSUE THREAD

**Issue by Hossam-EMostafa** [reviewx/Contribute#24]
Hi There 
i use ReviewX With custom post but I can’t submit a comment

**Comment by amin-abir** [comment]
Hi @Hossam-EMostafa 

Hope you are fine and doing great.

ReviewX can be used with the custom post, please check the doc https://reviewx.io/docs/how-to-use-reviewx-with-custom-post-types/, 
also this visual can be helpful I think, https://www.youtube.com/watch?v=jZ1X4GmJDhM

If you are facing the further issue, please contact our [support](https://reviewx.io/support/)

Thanks for using ReviewX.
