### ISSUE TITLE
Installed Pro Version of ReviewX triggers critical error

### ISSUE THREAD

**Issue by Arndt-** [reviewx/Contribute#25]
So I installed ReviewX Free Version a while ago and it worked perfectly.

Today I installed the Pro Version and it suddenly stopped working and destroys the website layout completely.

Using following Plugins:

- Elementor V 3.5.6 
- Elementor Pro V V 3.6.4
- NotificationX Free V 2.4.2
- NotificationX Pro V 2.5.2 
- ReviewX Free V 1.4.5
- ReviewX Pro V 1.3.3
- WooCommerce V 6.3.1 

So I created "Product Review Criteria" for **posts** with the Free Version first.
Then installed the Pro Version and all post pages and the layout a broken and triggering following error.
Then I deleted all the comments then the layout works again but the rating system isn't displayed at all.

For clarifying. 
I've created a custom Elementor template using the "posts comments widget" to show your rating-system.
But now it only says "There are no reviews yet." But discussion or commenting for posts is still activated.
Even disabling the Pro Plugin won't solve it...

___

**Fatal error: Uncaught Error: Call to undefined method ReviewX_Helper::country_flag() in public_html/wp-content/plugins/reviewx-pro/public/partials/single-review/style-one.php:197** 

Stack trace: #0 /public_html/wp-content/plugins/reviewx-pro/includes/features/class-rxpro-field-options.php(1652): include() #1 /public_html/wp-includes/class-wp-hook.php(307): ReviewXPro_Features->load_review_templates(1) 

#2 /public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters(1, Array) 
#3 /public_html/wp-content/plugins/reviewx/partials/storefront/product-reviews.php(81): apply_filters('rx_load_review_...', 1) 
#4 /public_html/wp-includes/comment-template.php(1554): require('/home/customer/...') 
#5 //public_html/wp-content/plugins/elementor-pro/modules/theme-elements/widgets/post-comments.php( in /public_html/wp-content/plugins/reviewx-pro/public/partials/single-review/style-one.php on line 197

**Comment by Arndt-** [comment]
**So I narrowed it down to:**

1. The review form will not be shown anymore once there was a rating which was deleted. 

2. If I create a new post the review form is visible but once I added a review the above error will be triggered again and then the review form won't be shown.

**Comment by amin-abir** [comment]
Hi @Arndt- 

Hope you are fine and doing great.😊

Sorry to hear about your inconvenience. 
ReviewX is compatible with those plugins mentioned above. I think there could be Elementor template issue, as currently, we provide custom addons for elementor which work on the WooCommerce product template. 
We need some more info regarding your site, can you please contact our https://reviewx.io/support/?

Thanks

**Comment by Arndt-** [comment]
Hey, I just sent you a support ticket, please check

**Comment by amin-abir** [comment]
The issue was plugin version related, which was solved by our support.

Thanks
