### ISSUE TITLE
Fix arrow margin left

### ISSUE THREAD

**Issue by devslayertech** [reviewx/Contribute#30]
Before:
![image](https://user-images.githubusercontent.com/100967476/163451868-f85be07f-9331-47cc-bc63-09c15a334223.png)

After:
![image](https://user-images.githubusercontent.com/100967476/163451917-ca58d982-d391-4380-ad30-b668d2e37c50.png)

CSS:
![image](https://user-images.githubusercontent.com/100967476/163451980-06af37a9-300c-4131-89fe-275efa738f99.png)

**Comment by amin-abir** [comment]
You are awesome, Thanks for the fixing.
