### ISSUE TITLE
reCaptcha not working

### ISSUE THREAD

**Issue by devslayertech** [reviewx/Contribute#31]
![image](https://user-images.githubusercontent.com/100967476/163454261-6abc0380-1515-4f7b-850f-6622d25ff92f.png)

Correct way to load reCaptcha v2 API:
![image](https://user-images.githubusercontent.com/100967476/163462752-109e59fd-166b-4da8-acd8-cc820d106b4b.png)

Missing specify version of reCaptcha in configuration => reCaptcha v2? reCaptcha v3?
![image](https://user-images.githubusercontent.com/100967476/163462567-4fcbfc34-1777-437c-a9c5-5adc82e4605f.png)

**Comment by amin-abir** [comment]
After introducing Google ReCaptcha v3, the issue is fixed.

Thanks
