### ISSUE TITLE
Dashboard Wordpress wrong after enable plugin

### ISSUE THREAD

**Issue by marcellovocale** [reviewx/Contribute#35]
Hi 
when I enable plugin my user dashboard of wordpress look wrong
I attach a image
https://ibb.co/hDVrLh4

How fix ? 
Thank you

**Comment by marcellovocale** [comment]
I have solved by CSS
```
.woocommerce-account .woocommerce-MyAccount-navigation{
	width:100%;
}
```

but I'm sure is your plugin that cause this problem because when deactivated, error style not appear (without CSS editing)

**Comment by amin-abir** [comment]
Hi @vucumbra 

Hope you are fine today.

Good to know you have solved the issue by yourself, much appreciated.👍🏻

On our end, I am unable to replicate the issue with only WooCommerce, ReviewX, and Storefront theme. Can you please tell us, which theme you are using? Although you have solved the issue and shared the solution, but it will help us to understand the scenario.

Thanks & regards

**Comment by marcellovocale** [comment]
Hi
I'm fine thank you, I hope you are fine too.

I use premium theme
https://themeforest.net/item/electro-electronics-store-woocommerce-theme/15720624
