### ISSUE TITLE
Show only 2 criteria in backend, but I have 3

### ISSUE THREAD

**Issue by marcellovocale** [reviewx/Contribute#36]
Show only 2 criteria in backend, but I have 3
I think is a bug
Can you fix?

![Progetto senza titolo](https://user-images.githubusercontent.com/25597471/185634645-9badb6e1-fa94-41bd-9091-8446861444d2.png)

**Comment by amin-abir** [comment]
Hi

We could not replicate the issue on our end. If you are facing the issue, please contact our support: https://reviewx.io/support/

Thanks

![at-1](https://user-images.githubusercontent.com/56829807/205562655-e19ea512-2d41-424c-95ae-10cf7c1c2634.gif)
