### ISSUE TITLE
Reviewx cpt addon not showing

### ISSUE THREAD

**Issue by FuturiaMarketing** [reviewx/Contribute#37]
Hi there, I have installed the plugin but only 2 addons are showing up, the elementor CPT addon just doesn't appear to be there.

**Comment by amin-abir** [comment]
Hi FuturiaMarketing

I think you are using the free version of ReviewX. Elementor CPT addon is a premium feature and is available in ReviewX Pro
Detail : https://reviewx.io/docs/how-to-use-reviewx-cpt-elementor-custom-widget/

Thanks
