### ISSUE TITLE
ReviewX PHP Error

### ISSUE THREAD

**Issue by startupweb** [reviewx/Contribute#40]
Hello,

I'm getting this error on ReviewX

wp-content/plugins/reviewx-pro/includes/features/class-rxpro-field-options.php

Screenshot
https://app.screencast.com/QLZzxf0t5GrUM

The only plugins installed are
woocommerce
elementor & pro
reviewx

Can you take a look at it?

It seems websites on the internet are having the same problem too.
https://ecledmall.com/product/150w-solar-powered-street-lights/

Thank you,
   wiL

**Comment by amin-abir** [comment]
Hi @startupweb 

Thanks for reporting the warning issue. As we are already contacting you over our support, so I will update you there.

Thanks
