### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by purcoir** [reviewx/Contribute#42]
ReviewX is causing styling issues for contact forms while using the Enfold theme. When forms are set to transparent background the ReviewX app is forcing a white background. 

<img width="1440" alt="Screenshot 2022-12-10 at 9 03 40 PM" src="https://user-images.githubusercontent.com/120288801/206883061-ab585722-7bcf-4009-9f3c-47ccee904a31.png">

**Comment by amin-abir** [comment]
Solved over our support.
