### ISSUE TITLE
Email Remainder NOT Saving Email Content Bug

### ISSUE THREAD

**Issue by Ashrakk** [reviewx/Contribute#5]
I edited the email content of the Remainder Email, Saved, Sent the test email (so far so good) but then, when i send it by using "Filter and send remainder"  the email sent does not correspond to the email i have saved but to the content and header that comes by default.

Settings
![image](https://user-images.githubusercontent.com/10323178/98161006-56ef5d80-1edf-11eb-9519-f1c58edd2598.png)

Email sent by test email feature
![image](https://user-images.githubusercontent.com/10323178/98161151-90c06400-1edf-11eb-87cf-e953d1a7a811.png)

Email sent to fake customer
![image](https://user-images.githubusercontent.com/10323178/98161085-771f1c80-1edf-11eb-9105-15910073c9b4.png)

**Comment by arnaimbd** [comment]
Hey @Ashrakk,
Sorry for the inconvenience. 
Please allow us some time, we'll inspect the issues from our side and will get back to you with details. 

Thanks for being with ReviewX.
Naim

**Comment by Ashrakk** [comment]
> 
> 
> Hey @Ashrakk,
> Sorry for the inconvenience.
> Please allow us some time, we'll inspect the issues from our side and will get back to you with details.
> 
> Thanks for being with ReviewX.
> Naim

Thank you, so far your plugin is great. 
Good luck in finding the issue
