### ISSUE TITLE
CSS broken with new Version

### ISSUE THREAD

**Issue by gzah3053** [reviewx/Contribute#6]
Hello, i just installed v1.2.2 and now a lot of things are broken.

- On the page "Kontakt" there are normally 2 columns on screens >992px (now there is only 1 column)
- footer is visible only on screens > 992px (now it is always visible)
- mobile-footer is visible only on screens <992px (now it is always visible)
- another footer bug => there is an element visible that is normally set to display: none;
- social media icons => are no more centered

Maybe there are a lot more bugs. This is a HUGE impact!!! like this the plugin is useless. Please check it out and fix it.

I tried to fix it => if i DEACTIVATE the following css style then it works as it should:

.ct-section > .ct-section-inner-wrap {
    display: flow-root !important;
}

you can check it out => https://biowax.ch

Thanks!

**Comment by amin-abir** [comment]
Hi @gzah3053 

Thanks for reporting this issue, highly appreciated.
We replied to you from our support mail regarding this issue.

Regards
