### ISSUE TITLE
reset option needed - deleted test reviews and star-ratings will be shown in products - why ?

### ISSUE THREAD

**Issue by Schmidtworks** [reviewx/Contribute#7]
Hi Amin 

need once more your support: 
for example
-> https://weingut-wagner.shop/produkt/lemberger-r-2016-trocken/

i've deleted the test-reviews but in the product sites the rating and notice of a review already appears - this should be able to delete - is there a reset option ? for all profiled products ?
![Bildschirmfoto 2020-11-19 um 11 50 22](https://user-images.githubusercontent.com/48754943/99657088-fbd07580-2a5d-11eb-8c1c-ab3d914863e0.png)
![Bildschirmfoto 2020-11-19 um 11 51 06](https://user-images.githubusercontent.com/48754943/99657109-012dc000-2a5e-11eb-9b97-501590d41166.png)

Thanx for your reply.
Fri

**Comment by amin-abir** [comment]
Hi @Schmidtworks 

Sorry for your inconvenience. Can you please check your deleted review in the trash folder. If still there the review in trash please delete that.

**Comment by Schmidtworks** [comment]
Hi Amin

No the trash is also already deleted.

You still have the login to look on the wordpress dashboard of this project – if you want.

[cid:image001.png@01D6BE70.77944A70]


---
Mit freundlichem Gruß

Friedhelm Schmidt
Geschäftsführer

Verstand für Marke und Mensch

Schmidtworks GmbH | Kommunikationsagentur

Werkstatt für Design und Botschaft
Ludwig-Mueller-Strasse 8
D-71723 Grossbottwar | Germany
+49 (0) 177.3274057
fs@schmidtworks.eu<mailto:fs@schmidtworks.eu>
https://schmidtworks.eu



Von: Amin <notifications@github.com>
Datum: Donnerstag, 19. November 2020 um 12:31
An: reviewx/Contribute <Contribute@noreply.github.com>
Cc: Schmidtworks <friedhelm@schmidt-works.de>, Mention <mention@noreply.github.com>
Betreff: Re: [reviewx/Contribute] reset option needed - deleted test reviews and star-ratings will be shown in products - why ? (#7)

Hi @Schmidtworks<https://github.com/Schmidtworks>

Sorry for your inconvenience. Can you please check your deleted review in the trash folder. If still there the review in trash please delete that.

**Comment by amin-abir** [comment]
Yes, we may need your site access. Please contact here, https://reviewx.io/support/ 
Our support member will take care of it.

**Comment by Schmidtworks** [comment]
ok - i've send the support ticket via https://reviewx.io/support/ - thanx for your help.
Login is already known on your side.
