### ISSUE TITLE
Upload image doest not have !

### ISSUE THREAD

**Issue by AlphaCyberTeam** [reviewx/Contribute#8]
Upload image doest not have ! Please check

**Comment by arnaimbd** [comment]
Hi @samvinh17, 
Thanks for reporting the issue👍  We'll inspect and take the necessary actions.
We will keep you posted.

**Comment by amin-abir** [comment]
Hi @samvinh17 

I have checked the image upload issue you are saying with the new version of ReviewX [v.1.2.4], but sorry I could not replicate this. Can you please save the image settings once again, and check it.

I have made a video for you with the latest plugin.
https://www.loom.com/share/178801bf4eab4581a3ec1055bcc3e1da

Thanks
