### ISSUE TITLE
Displaying Username instead of Customer Name in review

### ISSUE THREAD

**Issue by Prokreeger** [reviewx/Contribute#9]
Hi there,

When customer is logged in and leave a review, your plugin displayed in the Name field customers username.

How can I display customers First and Last name instead of username?

**Comment by amin-abir** [comment]
Hi @Prokreeger 

Currently, we do not have such an option or settings to display the customer's first name & last name. But we will add this as a feature where you can choose how you want to display the author name.

I will inform you once the feature is implemented.

Thanks
